version: '3.8'

services:
  anyalert:
    build: .
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./config.json:/root/config.json
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
